/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteDisclaimerRouteImport } from './routes/website-disclaimer'
import { Route as ThreatMapRouteImport } from './routes/threat-map'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResponsibleDisclosureRouteImport } from './routes/responsible-disclosure'
import { Route as PrivacyNoticeRouteImport } from './routes/privacy-notice'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as AdvisorAnalyticsRouteImport } from './routes/advisor-analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AiAdvisorIndexRouteImport } from './routes/ai-advisor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiAdvisorThreadIdRouteImport } from './routes/ai-advisor.$threadId'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAdvisorRouteImport } from './routes/admin.advisor'

const WebsiteDisclaimerRoute = WebsiteDisclaimerRouteImport.update({
  id: '/website-disclaimer',
  path: '/website-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatMapRoute = ThreatMapRouteImport.update({
  id: '/threat-map',
  path: '/threat-map',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleDisclosureRoute = ResponsibleDisclosureRouteImport.update({
  id: '/responsible-disclosure',
  path: '/responsible-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyNoticeRoute = PrivacyNoticeRouteImport.update({
  id: '/privacy-notice',
  path: '/privacy-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorAnalyticsRoute = AdvisorAnalyticsRouteImport.update({
  id: '/advisor-analytics',
  path: '/advisor-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorIndexRoute = AiAdvisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiAdvisorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorThreadIdRoute = AiAdvisorThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AiAdvisorRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvisorRoute = AdminAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor-analytics': typeof AdvisorAnalyticsRoute
  '/ai-advisor': typeof AiAdvisorRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/insights': typeof InsightsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/responsible-disclosure': typeof ResponsibleDisclosureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/threat-map': typeof ThreatMapRoute
  '/website-disclaimer': typeof WebsiteDisclaimerRoute
  '/admin/advisor': typeof AdminAdvisorRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/theme': typeof AdminThemeRoute
  '/ai-advisor/$threadId': typeof AiAdvisorThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-advisor/': typeof AiAdvisorIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/advisor-analytics': typeof AdvisorAnalyticsRoute
  '/auth': typeof AuthRouteWithChildren
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/insights': typeof InsightsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/responsible-disclosure': typeof ResponsibleDisclosureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/threat-map': typeof ThreatMapRoute
  '/website-disclaimer': typeof WebsiteDisclaimerRoute
  '/admin/advisor': typeof AdminAdvisorRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/theme': typeof AdminThemeRoute
  '/ai-advisor/$threadId': typeof AiAdvisorThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ai-advisor': typeof AiAdvisorIndexRoute
  '/blog': typeof BlogIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor-analytics': typeof AdvisorAnalyticsRoute
  '/ai-advisor': typeof AiAdvisorRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/insights': typeof InsightsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/responsible-disclosure': typeof ResponsibleDisclosureRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/threat-map': typeof ThreatMapRoute
  '/website-disclaimer': typeof WebsiteDisclaimerRoute
  '/admin/advisor': typeof AdminAdvisorRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/theme': typeof AdminThemeRoute
  '/ai-advisor/$threadId': typeof AiAdvisorThreadIdRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ai-advisor/': typeof AiAdvisorIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/advisor-analytics'
    | '/ai-advisor'
    | '/auth'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/insights'
    | '/privacy-notice'
    | '/responsible-disclosure'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/threat-map'
    | '/website-disclaimer'
    | '/admin/advisor'
    | '/admin/blog'
    | '/admin/leads'
    | '/admin/pages'
    | '/admin/theme'
    | '/ai-advisor/$threadId'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/ai-advisor/'
    | '/blog/'
    | '/industries/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/advisor-analytics'
    | '/auth'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/insights'
    | '/privacy-notice'
    | '/responsible-disclosure'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/threat-map'
    | '/website-disclaimer'
    | '/admin/advisor'
    | '/admin/blog'
    | '/admin/leads'
    | '/admin/pages'
    | '/admin/theme'
    | '/ai-advisor/$threadId'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/admin'
    | '/ai-advisor'
    | '/blog'
    | '/industries'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/advisor-analytics'
    | '/ai-advisor'
    | '/auth'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/insights'
    | '/privacy-notice'
    | '/responsible-disclosure'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/threat-map'
    | '/website-disclaimer'
    | '/admin/advisor'
    | '/admin/blog'
    | '/admin/leads'
    | '/admin/pages'
    | '/admin/theme'
    | '/ai-advisor/$threadId'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/ai-advisor/'
    | '/blog/'
    | '/industries/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvisorAnalyticsRoute: typeof AdvisorAnalyticsRoute
  AiAdvisorRoute: typeof AiAdvisorRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  InsightsRoute: typeof InsightsRoute
  PrivacyNoticeRoute: typeof PrivacyNoticeRoute
  ResponsibleDisclosureRoute: typeof ResponsibleDisclosureRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  ThreatMapRoute: typeof ThreatMapRoute
  WebsiteDisclaimerRoute: typeof WebsiteDisclaimerRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website-disclaimer': {
      id: '/website-disclaimer'
      path: '/website-disclaimer'
      fullPath: '/website-disclaimer'
      preLoaderRoute: typeof WebsiteDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-map': {
      id: '/threat-map'
      path: '/threat-map'
      fullPath: '/threat-map'
      preLoaderRoute: typeof ThreatMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-disclosure': {
      id: '/responsible-disclosure'
      path: '/responsible-disclosure'
      fullPath: '/responsible-disclosure'
      preLoaderRoute: typeof ResponsibleDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-notice': {
      id: '/privacy-notice'
      path: '/privacy-notice'
      fullPath: '/privacy-notice'
      preLoaderRoute: typeof PrivacyNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor-analytics': {
      id: '/advisor-analytics'
      path: '/advisor-analytics'
      fullPath: '/advisor-analytics'
      preLoaderRoute: typeof AdvisorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor/': {
      id: '/ai-advisor/'
      path: '/'
      fullPath: '/ai-advisor/'
      preLoaderRoute: typeof AiAdvisorIndexRouteImport
      parentRoute: typeof AiAdvisorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor/$threadId': {
      id: '/ai-advisor/$threadId'
      path: '/$threadId'
      fullPath: '/ai-advisor/$threadId'
      preLoaderRoute: typeof AiAdvisorThreadIdRouteImport
      parentRoute: typeof AiAdvisorRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advisor': {
      id: '/admin/advisor'
      path: '/advisor'
      fullPath: '/admin/advisor'
      preLoaderRoute: typeof AdminAdvisorRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdvisorRoute: typeof AdminAdvisorRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdvisorRoute: AdminAdvisorRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiAdvisorRouteChildren {
  AiAdvisorThreadIdRoute: typeof AiAdvisorThreadIdRoute
  AiAdvisorIndexRoute: typeof AiAdvisorIndexRoute
}

const AiAdvisorRouteChildren: AiAdvisorRouteChildren = {
  AiAdvisorThreadIdRoute: AiAdvisorThreadIdRoute,
  AiAdvisorIndexRoute: AiAdvisorIndexRoute,
}

const AiAdvisorRouteWithChildren = AiAdvisorRoute._addFileChildren(
  AiAdvisorRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvisorAnalyticsRoute: AdvisorAnalyticsRoute,
  AiAdvisorRoute: AiAdvisorRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  InsightsRoute: InsightsRoute,
  PrivacyNoticeRoute: PrivacyNoticeRoute,
  ResponsibleDisclosureRoute: ResponsibleDisclosureRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  ThreatMapRoute: ThreatMapRoute,
  WebsiteDisclaimerRoute: WebsiteDisclaimerRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
